### ISSUE TITLE
Create UI tests

### ISSUE THREAD

**Issue by KostyalBalint** [BME-MIT-IET/iet-hf-2023-ajandekutalvany#4]
Create UI tests for the frontend. 

I think the [React Testing Lib](https://testing-library.com/) could be used for this

Acceptance criteria: 
- The main site should have a create button
- Pressing the button should open a modal
- The modal should have fields for creating a plant
- The plant page should show the name
- Tha plant page should show the required watering frequency

**Comment by Taurusz1** [comment]
#11 solved this

**Comment by Taurusz1** [comment]
#11 solved this
